// Tema 8/1.tiendaGuitarras/src/components/Guitarra.vue
<script setup>
// Definimos los props para recibir datos del padre
const props = defineProps({
  guitarra: {
    type: Object,
    required: true,
  },
});

// Definimos los emits para enviar eventos al padre
defineEmits(["agregar-carrito"]);
</script>

<template>
  <div class="col-md-6 col-lg-4 my-4 row align-items-center">
    <div class="col-4">
      <img
        class="img-fluid"
        :src="'/img/' + guitarra.imagen + '.jpg'"
        :alt="'imagen guitarra ' + guitarra.nombre"
      />
    </div>
    <div class="col-8">
      <h3 class="text-black fs-4 fw-bold text-uppercase">
        {{ guitarra.nombre }}
      </h3>
      <p>{{ guitarra.descripcion }}</p>
      <p class="fw-black text-primary fs-3">{{ guitarra.precio }}€</p>
      <button
        type="button"
        class="btn btn-dark w-100"
        @click="$emit('agregar-carrito', guitarra)"
      >
        Agregar al Carrito
      </button>
    </div>
  </div>
</template>

// Tema 7/1. Tienda de Guitarras Ficheros-20251117/tiendaGuitarra/src/components/Guitarra.jsx
export default function Guitarra({guitarraObj, carrito, setCarrito}) {

    const {id, name, image, description, price} = guitarraObj;

    const handleClick = (id) => {
        console.log(`Desde click a ${id}`);
        setCarrito([...carrito, guitarraObj]);
    }

    return(
            <div className="col-md-6 col-lg-4 my-4 row align-items-center">
                <div className="col-4">
                    <img className="img-fluid" src={`/img/${image}.jpg`} alt="imagen guitarra" />
                </div>
                <div className="col-8">
                    <h3 className="text-black fs-4 fw-bold text-uppercase">{name}</h3>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sit quae labore odit magnam in autem nesciunt, amet deserunt</p>
                    <p className="fw-black text-primary fs-3">{price}€</p>
                    <button 
                        type="button"
                        className="btn btn-dark w-100"
                        onClick={() => handleClick(id)}
                    >Agregar al Carrito</button>
                </div>
            </div>
    )
}
