// Tema 7/1. Tienda de Guitarras Ficheros-20251117/tiendaGuitarra/src/components/Header.jsx
export default function Header({carrito}) {
  const carritoVacio = useMemo (() => carrito.lenght === 0, [carrito]);
  const carritoTotal = () =>
    carrito.reduce(
      (total, element) => total + (element.cantidad * element.price),
      0
    );

  return (
    <header className="py-5 header">
      <div className="container-xl">
        <div className="row justify-content-center justify-content-md-between">
          <div className="col-8 col-md-3">
            <a href="#">
              <img
                className="img-fluid"
                src="/img/logo.svg"
                alt="imagen logo"
              />
            </a>
          </div>
          <nav className="col-md-6 mt-5 d-flex align-items-start justify-content-end">
            <div className="carrito">
              <img
                className="img-fluid"
                src="/img/carrito.png"
                alt="imagen carrito"
              />

              <div id="carrito" className="bg-white p-3">
                {carritoVacio ? (
                  <p className="text-center">El carrito esta vacio</p>
                ) : (
                  <>
                    <table className="w-100 table">
                      <thead>
                        <tr>
                          <th>Imagen</th>
                          <th>Nombre</th>
                          <th>Precio</th>
                          <th>Cantidad</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        {carrito.map((element) => (
                          <tr key={element.id}>
                            <td>
                              <img
                                className="img-fluid"
                                src={`/img/${element.image}.jpg`}
                                alt="imagen guitarra"
                              />
                            </td>
                            <td>{element.name}</td>
                            <td className="fw-bold">{element.price}€</td>
                            <td className="d-flex align-items-center gap-2">
                              <button type="button" className="btn btn-dark">
                                -
                              </button>
                              {element.cantidad}
                              <button type="button" className="btn btn-dark">
                                +
                              </button>
                            </td>
                            <td>
                              <button className="btn btn-danger" type="button">
                                X
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>

                    <p className="text-end">
                      Total pagar:{" "}
                      <span className="fw-bold">
                        {carrito.reduce(
                          (total, guitarra) => total + guitarra.price,
                          0
                        )}
                        €
                      </span>
                    </p>
                    <button
                      className="btn btn-dark w-100 mt-3 p-2"
                      onClick={() => setCarrito([])}
                    >
                      Vaciar Carrito
                    </button>
                  </>
                )}
              </div>
            </div>
          </nav>
        </div>
      </div>
    </header>
  );
}

// Tema 8/1. Tienda Guitarras Ficheros/vite-project/src/components/Header.vue
<script setup>
import { computed } from "vue";

const props = defineProps({
  carrito: {
    type: Array,
    required: true,
  },
  guitarra: {
    type: Object,
    required: true,
  },
});

defineEmits([
  "incrementar-cantidad",
  "decrementar-cantidad",
  "agregar-carrito",
  "eliminar-producto",
  "vaciar-carrito",
]);

const totalPagar = computed(() => {
  return props.carrito.reduce(
    (total, producto) => total + producto.cantidad * producto.precio,
    0
  );
});
</script>

<template>
  <header class="py-5 header">
    <div class="container-xl">
      <div class="row justify-content-center justify-content-md-between">
        <div class="col-8 col-md-3">
          <a href="index.html">
            <img class="img-fluid" src="/img/logo.svg" alt="imagen logo" />
          </a>
        </div>
        <nav
          class="col-md-6 a mt-5 d-flex align-items-start justify-content-end"
        >
          <div class="carrito">
            <img
              class="img-fluid"
              src="/img/carrito.png"
              alt="imagen carrito"
            />

            <div id="carrito" class="bg-white p-3">
              <p v-if="carrito.length === 0" class="text-center m-0">
                El carrito esta vacio
              </p>
              <div v-else>
                <table class="w-100 table">
                  <thead>
                    <tr>
                      <th>Imagen</th>
                      <th>Nombre</th>
                      <th>Precio</th>
                      <th>Cantidad</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="producto in carrito">
                      <td>
                        <img
                          class="img-fluid"
                          :src="'/img/' + producto.imagen + '.jpg'"
                          :alt="'imagen guitarra ' + producto.nombre"
                        />
                      </td>
                      <td>{{ producto.nombre }}</td>
                      <td class="fw-bold">{{ producto.precio }}€</td>
                      <td class="flex align-items-start gap-4">
                        <button
                          type="button"
                          class="btn btn-dark"
                          @click="$emit('decrementar-cantidad', producto.id)"
                        >
                          -
                        </button>
                        {{ producto.cantidad }}
                        <button
                          type="button"
                          class="btn btn-dark"
                          @click="$emit('incrementar-cantidad', producto.id)"
                        >
                          +
                        </button>
                      </td>
                      <td>
                        <button
                          class="btn btn-danger"
                          type="button"
                          @click="$emit('eliminar-producto', producto.id)"
                        >
                          X
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>

                <p class="text-end">
                  Total pagar: <span class="fw-bold">{{ totalPagar }}€</span>
                </p>
                <button
                  class="btn btn-dark w-100 mt-3 p-2"
                  @click="$emit('vaciar-carrito')"
                >
                  Vaciar Carrito
                </button>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <!--.row-->

      <div class="row mt-5">
        <div class="col-md-6 text-center text-md-start pt-5">
          <h1 class="display-2 fw-bold">Modelo {{ guitarra.nombre }}</h1>
          <p class="mt-5 fs-5 text-white">
            {{ guitarra.descripcion }}
          </p>
          <p class="text-primary fs-1 fw-black">{{ guitarra.precio }}€</p>
          <button
            type="button"
            class="btn fs-4 bg-primary text-white py-2 px-5"
            @click="$emit('agregar-carrito', guitarra)"
          >
            Agregar al Carrito
          </button>
        </div>
      </div>
    </div>

    <img
      class="header-guitarra"
      src="/img/header_guitarra.png"
      alt="imagen header"
    />
  </header>
</template>

<style lang="scss" scoped></style>
